[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.ruff]
line-length = 120
extend-ignore = [
	"E402", # Bottom imports
]
